---
version: "3.9"
services:
  web:
    image: nginx
    container_name: aer-nginx
    volumes: ["/home/aer/Downloads/nginx:/usr/share/nginx/html"]
    ports: ["8000:80"]
  database:
    image: postgres
    container_name: aer-postgres
    ports: ["5432:5432"]
    volumes: ["/home/aer/Downloads:/docker-entrypoint-initdb.d"]
    environment:
      POSTGRES_USER: "aeruser"
      POSTGRES_PASSWORD: "aer"
      POSTGRES_DB: "aerdb"
...
