---
 - hosts: node
   become: yes
   become_method: su
   become_user: root
   name: Setting up Docker Compose
   tasks:
     - name: Install Docker Compose
       get_url: 
         url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
         dest: /usr/local/bin/docker-compose
         mode: 755

