CREATE SCHEMA COLLEGE;

CREATE TABLE COLLEGE.STUDENTS (
	SID INT PRIMARY KEY,
	FIRSTNAME VARCHAR(20) NOT NULL,
	LASTNAME VARCHAR(20) NOT NULL
);

INSERT INTO COLLEGE.STUDENTS (SID, FIRSTNAME, LASTNAME) VALUES (1, 'aer','aye');
INSERT INTO COLLEGE.STUDENTS (SID, FIRSTNAME, LASTNAME) VALUES (2, 'yen','aye');
