---
  - hosts: node
    become: true
    become_method: su
    become_user: root
    vars_files:
     - /etc/ansible/playbooks/vars/aerbuntu-pass.yml
    vars:
      ansible_become_pass: '{{password}}'
    tasks:
      - name: Create directory to store files
        file:
          path: /home/aer/cfg
          state: directory      
