---
 - hosts: node
   become: true
   become_method: su
   become_user: root
   vars_files:
     - /etc/ansible/playbooks/vars/aerbuntu-pass.yml
   vars:
     ansible_become_pass: '{{password}}'
   name: Setting up Docker Compose
   tasks:
     - name: Install Docker Compose and psycopg2 with pip
       pip:
         name: docker-compose
         state: present
