---
 - hosts: node
   become: true
   become_method: su
   become_user: root
   vars_files:
    - /etc/ansible/playbooks/vars/aerbuntu-pass.yml
   vars:
     ansible_become_pass: '{{password}}' 
   tasks:
    - name: Install aptitude
      apt: 
        name: aptitude
        state: present
        update_cache: yes
        force_apt_get: yes
    - name: Install system packages
      apt:
        name: ['python3','apt-transport-https','ca-certificates','curl','software-properties-common','gnupg','lsb-release','python3-pip','python3-setuptools']     
        state: present
    - name: Install psycopg2-library, a prerequisite for PostgreSQL
      pip:
        name: psycopg2-binary
        state: present
    - name: Add Docker GPG
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: Install Docker with pip
      pip:
        name: docker
    - name: Install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: yes
...
